### ISSUE TITLE
Don't record processed reports that are rejected

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#201]
This came up in review of https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/395: We will probably be introducing protocols semantics around data recovery that will require us to reprocess reports under certain circumstances. In any case, we don't need to prevent replay of reports we don't use; and recording this information is slightly worrying as a DOS vector.

**Comment by cjpatton** [comment]
Here is the comment where I noticed this: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/395#discussion_r1081652456

**Comment by bhalleycf** [comment]
I'm not sure this is worth fixing.  It introduces a good bit of complexity since "has this been processed" is one of the early checks.  Reordering to set the processed status after the other early checks is possible, but has to be prepared to turn into an early failure itself as it could be a report id is being processed in parallel; whoever updates the DO first wins, but the other ones have to become failures.  I don't think the DoS risk is more than other risks we have to take.  My inclination is not to change things, but I could be wrong!

**Comment by cjpatton** [comment]
Hmm yeah I agree. Let's plan on discussing this at the DAP sync with ISRG/Mozilla next Tuesday. Perhaps there's something we're missing.
