### ISSUE TITLE
Use `--experimental-local` for wrangler E2E tests

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#258]
This runs the actual Workers daemon and is a more realistic simulation of the production environment

**Comment by bhalleycf** [comment]
There is a patch to do this on the bhalley/experimental-local branch.  It seems like an improvement, as while all tests pass with 0.0.12 and 0.0.15, the problems in 0.0.14 which did not show up with "--local" testing cause "--experimental-local" to fail immediately with the same error we saw from real workers.

Two basic things are needed:

1) For now, ignore errors from DO get_alarm() in "dev" deployments, as the experimental-local branch doesn't have alarm support yet.
2) Assign different ids and preview_ids (preview_id seems to be what get used) to the KV spaces for leader and helper, so that they are independent.  (Using the prior code value of "<ignore>" for both results in them using the same space and the helper getting errors when it tries to configure a task that the leader already configured.)

The diff is slightly larger due to the editor reformatting the wrangler.toml file into standard toml form.

**Comment by bhalleycf** [comment]
This was done in PR #260

**Comment by cjpatton** [comment]
I wonder if we should update documentation and maybe the dockerfile to use the new flag?

**Comment by bhalleycf** [comment]
Once someone besides me has had it work for them, I am all for that :)
