### ISSUE TITLE
Janus interop: Leader hangs on collect requests (flaky)

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/daphne#73]
@BranLwyd is working on Daphne <-> Janus interop tests. One test exercises a flaky bug in Daphne's Leader that causes collect requests to hang indefinitely:

To reproduce, checkout https://github.com/divviup/janus/tree/bran/revise-integration-test and run 
```
cargo test -p monolithic_integration_test daphne_janus -- --nocapture
```
Note that you may need to update `monolothic_integration_test/artificats/daphne_compiled`. This can be done by running `worker-build` in our `daphne_worker_test` directory and copying the contents of `build/worker`.

The bug is likely to happen after about 50 trials or so. You should see something like this:
```
thread 'daphne_janus' panicked at 'assertion failed: Instant::now() < collect_job_poll_timeout', monolithic_integration_test/tests/common/mod.rs:220:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Thu Aug 04 2022 12:26:53 GMT-0700 (Pacific Daylight Time) - [/internal/process], located at: (30.2713, -97.7426), within: Texas
DAP_ENV: Hostname override applied
agg job queue: []
```

Notes:
* We noticed that in cases where the bug occurs, not all of the reports get aggregated. We consistently see 45, but expect 46 in the batch.
* Something to investigatge is whether calls to DaphneWorkerConfig::durable_obejct are deadlocking. In fact a mutex here may not be appropriate.
* The bug may be an artifact of miniflare and might not manifest in the live deployment.

**Comment by cjpatton** [comment]
No additional bugs have been observed so far. In particular, Janus-Leader <-> Daphne-Helper has seen no issues.

**Comment by BranLwyd** [comment]
I poked at this for a while and I think I found a likely root cause. I think there is a race condition between writing a report to a bucket (which potentially populates the aggregate job queue, done during `/upload` handling) & draining the bucket of reports (done during `/internal/process` handling to create/run aggregate jobs).

Specifically, commenting out the highlighted lines of code causes the integration test to pass without flakes: https://github.com/cloudflare/daphne/blob/06c67f0cfae2b2102bdb4e844bcb0cf4620d11a9/daphne_worker/src/durable/report_store.rs#L118-L128 (this isn't a good long-term fix, since I suppose we'd never stop looking at empty buckets, but it serves to implicate this functionality as the cause of the issue)

I think the code that is being raced with is here: https://github.com/cloudflare/daphne/blob/06c67f0cfae2b2102bdb4e844bcb0cf4620d11a9/daphne_worker/src/durable/report_store.rs#L138-L172

And the order of events is roughly:
1. A call is made to `/upload`; the code eventually makes its way to the [`DURABLE_REPORT_STORE_PUT_PENDING` handler](https://github.com/cloudflare/daphne/blob/06c67f0cfae2b2102bdb4e844bcb0cf4620d11a9/daphne_worker/src/durable/report_store.rs#L138) which begins writing the report to a durable object. In this scenario, the bucket already exists & is populated on the aggregate job queue, so this handler will not attempt to write to the aggregate job queue.
1. Concurrently, a call is made to `/internal/process`; the code eventually makes its way to the [`DURABLE_REPORT_STORE_GET_PENDING` handler](https://github.com/cloudflare/daphne/blob/06c67f0cfae2b2102bdb4e844bcb0cf4620d11a9/daphne_worker/src/durable/report_store.rs#L89). This handler drains existing reports, but due to eventual-consistency/transactionality, does not see the report concurrently being written by the previous step. It believes it has emptied the bucket and deletes the bucket from the aggregate job queue.
1. Since the bucket is no longer in the aggregate job queue, it will never be considered 
for aggregation & the report written in the first step is effectively lost.

Recommendations:
1. If possible, make updating the aggregation job queue transactional with updating the reports in the bucket. I'm not an expert at CF Workers' Durable Objects, but I think DO transactionality only works within a given DO namespace -- this suggestion might (unfortunately) entail coalescing some of the existing namespaces together.
1. If the previous solution is infeasible, perhaps scanning the existing buckets looking for buckets with non-empty pending sets would be acceptable? It's less performant in that you need to examine buckets which will be empty (which will become more & more important as more buckets are introduced), but it would sidestep the transactionality concerns.

**Comment by cjpatton** [comment]
I see why this would cause a report to get orphaned in an unqueued bucket, but why would this cause collect requests to hang?

**Comment by cjpatton** [comment]
@BranLwyd I've implemented a a temporary fix that should unblock you. However it'll require some changes to the configuration of Daphne in your interop tests. I will send you a PR once the fix gets merged.

> If possible, make updating the aggregation job queue transactional with updating the reports in the bucket. I'm not an expert at CF Workers' Durable Objects, but I think DO transactionality only works within a given DO namespace ...

My understanding is that requests to a given DO instance are not supposed to run concurrently. From the [Workers docs](https://developers.cloudflare.com/workers/learning/using-durable-objects/):

> Global Uniqueness guarantees that there will be a single instance of a Durable Object class with a given ID running at once, across the world. Requests for a Durable Object ID are routed by the Workers runtime to the Cloudflare data center that owns the Durable Object.

I may be misunderstanding this, however.

**Comment by BranLwyd** [comment]
I added this to the PR as well, but I think the issue isn't that we have two concurrent requests to a single DO instance running simultaneously (which, I agree, shouldn't be possible per the DO docs) -- it's that the `ReportShare` DO implementation will also update the `LeaderAggregationJobQueue` DO, and updating _two different_ DO instances has no transactionality guarantees. I added a more detailed comment to #75.

**Comment by cjpatton** [comment]
Yeah this is tricky.
